#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Command {
    // Navigation
    SelectNextRow,
    SelectPrevRow,
    SelectFirstRow,
    SelectLastRow,
    NextPage,
    PrevPage,
    ClearSelection,

    // Actions
    OpenSelectedTask,
    OpenTaskEdit,
    CreateTask,
    DeleteSelectedTask,
    Sync,

    // Focus
    FocusSearch,
    FocusTable,
    FocusTableHeaders,
    FocusSidebar,
    FocusSidebarProjects,
    FocusSidebarTags,
    BlurInput,

    // Modal
    CloseModal,
    SaveModal,
    ModalScrollUp,
    ModalScrollDown,
    EnterEditMode,
    ExitEditField,
    EnterEditField,
    ModalFocusNext,
    ModalFocusPrev,
    SubmitOrExitField,
    ModalItemPrev,
    ModalItemNext,
    DeleteSelectedItem,
    EditSelectedItem,
    CopySelectedItem,
    ConfirmYes,
    ConfirmNo,
    Undo,
    Redo,

    // Filter
    ApplySearch,
    ClearFilters,
    ClearAllFilters,
    ClearProjectFilter,
    ClearTagFilter,
    ClearSearchAndDropdowns,
    FocusFilterNext,
    FocusFilterPrev,
    ToggleDropdown,
    SelectNextOption,
    SelectPrevOption,

    // Projects
    ExpandProject,
    CollapseProject,

    // Table Headers
    HeaderMoveNext,
    HeaderMovePrev,
    HeaderCycleSortOrder,
}

impl Command {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "SelectNextRow" => Some(Self::SelectNextRow),
            "SelectPrevRow" => Some(Self::SelectPrevRow),
            "SelectFirstRow" => Some(Self::SelectFirstRow),
            "SelectLastRow" => Some(Self::SelectLastRow),
            "NextPage" => Some(Self::NextPage),
            "PrevPage" => Some(Self::PrevPage),
            "ClearSelection" => Some(Self::ClearSelection),
            "OpenSelectedTask" => Some(Self::OpenSelectedTask),
            "OpenTaskEdit" => Some(Self::OpenTaskEdit),
            "CreateTask" => Some(Self::CreateTask),
            "DeleteSelectedTask" => Some(Self::DeleteSelectedTask),
            "Sync" => Some(Self::Sync),
            "FocusSearch" => Some(Self::FocusSearch),
            "FocusTable" => Some(Self::FocusTable),
            "FocusTableHeaders" => Some(Self::FocusTableHeaders),
            "FocusSidebar" => Some(Self::FocusSidebar),
            "FocusSidebarProjects" => Some(Self::FocusSidebarProjects),
            "FocusSidebarTags" => Some(Self::FocusSidebarTags),
            "BlurInput" => Some(Self::BlurInput),
            "CloseModal" => Some(Self::CloseModal),
            "SaveModal" => Some(Self::SaveModal),
            "ModalScrollUp" => Some(Self::ModalScrollUp),
            "ModalScrollDown" => Some(Self::ModalScrollDown),
            "EnterEditMode" => Some(Self::EnterEditMode),
            "ExitEditField" => Some(Self::ExitEditField),
            "EnterEditField" => Some(Self::EnterEditField),
            "ModalFocusNext" => Some(Self::ModalFocusNext),
            "ModalFocusPrev" => Some(Self::ModalFocusPrev),
            "SubmitOrExitField" => Some(Self::SubmitOrExitField),
            "ModalItemPrev" => Some(Self::ModalItemPrev),
            "ModalItemNext" => Some(Self::ModalItemNext),
            "DeleteSelectedItem" => Some(Self::DeleteSelectedItem),
            "EditSelectedItem" => Some(Self::EditSelectedItem),
            "CopySelectedItem" => Some(Self::CopySelectedItem),
            "ConfirmYes" => Some(Self::ConfirmYes),
            "ConfirmNo" => Some(Self::ConfirmNo),
            "Undo" => Some(Self::Undo),
            "Redo" => Some(Self::Redo),
            "ApplySearch" => Some(Self::ApplySearch),
            "ClearFilters" => Some(Self::ClearFilters),
            "ClearAllFilters" => Some(Self::ClearAllFilters),
            "ClearProjectFilter" => Some(Self::ClearProjectFilter),
            "ClearTagFilter" => Some(Self::ClearTagFilter),
            "ClearSearchAndDropdowns" => Some(Self::ClearSearchAndDropdowns),
            "FocusFilterNext" => Some(Self::FocusFilterNext),
            "FocusFilterPrev" => Some(Self::FocusFilterPrev),
            "ToggleDropdown" => Some(Self::ToggleDropdown),
            "SelectNextOption" => Some(Self::SelectNextOption),
            "SelectPrevOption" => Some(Self::SelectPrevOption),
            "ExpandProject" => Some(Self::ExpandProject),
            "CollapseProject" => Some(Self::CollapseProject),
            "HeaderMoveNext" => Some(Self::HeaderMoveNext),
            "HeaderMovePrev" => Some(Self::HeaderMovePrev),
            "HeaderCycleSortOrder" => Some(Self::HeaderCycleSortOrder),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::SelectNextRow => "SelectNextRow",
            Self::SelectPrevRow => "SelectPrevRow",
            Self::SelectFirstRow => "SelectFirstRow",
            Self::SelectLastRow => "SelectLastRow",
            Self::NextPage => "NextPage",
            Self::PrevPage => "PrevPage",
            Self::ClearSelection => "ClearSelection",
            Self::OpenSelectedTask => "OpenSelectedTask",
            Self::OpenTaskEdit => "OpenTaskEdit",
            Self::CreateTask => "CreateTask",
            Self::DeleteSelectedTask => "DeleteSelectedTask",
            Self::Sync => "Sync",
            Self::FocusSearch => "FocusSearch",
            Self::FocusTable => "FocusTable",
            Self::FocusTableHeaders => "FocusTableHeaders",
            Self::FocusSidebar => "FocusSidebar",
            Self::FocusSidebarProjects => "FocusSidebarProjects",
            Self::FocusSidebarTags => "FocusSidebarTags",
            Self::BlurInput => "BlurInput",
            Self::CloseModal => "CloseModal",
            Self::SaveModal => "SaveModal",
            Self::ModalScrollUp => "ModalScrollUp",
            Self::ModalScrollDown => "ModalScrollDown",
            Self::EnterEditMode => "EnterEditMode",
            Self::ExitEditField => "ExitEditField",
            Self::EnterEditField => "EnterEditField",
            Self::ModalFocusNext => "ModalFocusNext",
            Self::ModalFocusPrev => "ModalFocusPrev",
            Self::SubmitOrExitField => "SubmitOrExitField",
            Self::ModalItemPrev => "ModalItemPrev",
            Self::ModalItemNext => "ModalItemNext",
            Self::DeleteSelectedItem => "DeleteSelectedItem",
            Self::EditSelectedItem => "EditSelectedItem",
            Self::CopySelectedItem => "CopySelectedItem",
            Self::ConfirmYes => "ConfirmYes",
            Self::ConfirmNo => "ConfirmNo",
            Self::Undo => "Undo",
            Self::Redo => "Redo",
            Self::ApplySearch => "ApplySearch",
            Self::ClearFilters => "ClearFilters",
            Self::ClearAllFilters => "ClearAllFilters",
            Self::ClearProjectFilter => "ClearProjectFilter",
            Self::ClearTagFilter => "ClearTagFilter",
            Self::ClearSearchAndDropdowns => "ClearSearchAndDropdowns",
            Self::FocusFilterNext => "FocusFilterNext",
            Self::FocusFilterPrev => "FocusFilterPrev",
            Self::ToggleDropdown => "ToggleDropdown",
            Self::SelectNextOption => "SelectNextOption",
            Self::SelectPrevOption => "SelectPrevOption",
            Self::ExpandProject => "ExpandProject",
            Self::CollapseProject => "CollapseProject",
            Self::HeaderMoveNext => "HeaderMoveNext",
            Self::HeaderMovePrev => "HeaderMovePrev",
            Self::HeaderCycleSortOrder => "HeaderCycleSortOrder",
        }
    }
}
